// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using Core.Entities;

namespace Entity
{
    public partial class tblyonetmenlik :IEntity
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Url { get; set; }
    }
}